
import Header from '../header/header';
import Footer from '../footer/footer';
import '../css/Terms.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  return (

        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
          <Header />
          <div >
            <div className="gdf">
            {children}
            </div>
          </div>
          <Footer />
        </div>
    
  );
};

export default RootLayout;
